In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available()) # 返回True就是GPU可用
print(torch.version.cuda)

2.14.0+cu132
True
13.2


In [22]:
x = torch.rand(4, 3) 
print(x)

tensor([[0.5913, 0.3221, 0.1573],
        [0.2514, 0.4358, 0.2181],
        [0.4684, 0.5060, 0.0198],
        [0.1229, 0.9998, 0.8891]])


In [4]:
x = torch.zeros(4, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) 
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = torch.ones(4, 3, dtype=torch.double) 
# 创建一个新的全1矩阵tensor，返回的tensor默认具有相同的torch.dtype和torch.device
# 也可以像之前的写法 x = torch.ones(4, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
# 重置数据类型
print(x)
# 结果会有一样的size
# 获取它的维度信息
print(x.size())
print(x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6665, -0.6801,  0.7738],
        [ 1.0504,  1.0539,  1.5540],
        [-0.0610, -0.5271,  0.6706],
        [-2.4806, -0.1926,  0.8220]])
torch.Size([4, 3])
torch.Size([4, 3])


In [ ]:
y = torch.rand(4, 3) 
print(y)
print(x + y)

# 方式2
print(torch.add(x, y))

# 方式3 in-place，原值修改
y.add_(x) 
print(y)

tensor([[0.0024, 0.9784, 0.9313],
        [0.7257, 0.8920, 0.1684],
        [0.7349, 0.9923, 0.2513],
        [0.7213, 0.5816, 0.0035]])
tensor([[0.5937, 1.3004, 1.0887],
        [0.9772, 1.3278, 0.3865],
        [1.2033, 1.4982, 0.2711],
        [0.8442, 1.5814, 0.8926]])
tensor([[0.5937, 1.3004, 1.0887],
        [0.9772, 1.3278, 0.3865],
        [1.2033, 1.4982, 0.2711],
        [0.8442, 1.5814, 0.8926]])
tensor([[0.5937, 1.3004, 1.0887],
        [0.9772, 1.3278, 0.3865],
        [1.2033, 1.4982, 0.2711],
        [0.8442, 1.5814, 0.8926]])


In [38]:
z=y.unsqueeze(1)
print(z)
print(z.shape)

tensor([[[0.5937, 1.3004, 1.0887]],

        [[0.9772, 1.3278, 0.3865]],

        [[1.2033, 1.4982, 0.2711]],

        [[0.8442, 1.5814, 0.8926]]])
torch.Size([4, 1, 3])
